tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
brew "mas"
cask "iterm2"
cask "google-chrome"
cask "rectangle"
cask "docker"
cask "jetbrains-toolbox"
cask "visual-studio-code"
cask "android-studio"
cask "slack"
cask "karabiner-elements"
cask "postman"
cask "font-d2coding"
mas "KakaoTalk", id: 869223134
mas "Xcode", id: 497799835